runtime: python310
env: standard
entrypoint: gunicorn -b :$PORT tripagenda.asgi:app -k uvicorn.workers.UvicornWorker
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.85
  min_instances: 1
  max_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

env_variables:
  APPENGINE_URL: https://fastdjango.uc.r.appspot.com
  ENVIRONMENT: production
