runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  INSTANCE_CONNECTION_NAME: resolute-tracer-402011:europe-west1:travelmate-backend-gpt
  DB_USER: Karel  
  DB_PASS: fghjk56789$$!!
  DB_NAME: postgres

handlers:
- url: /.*
  script: auto