# Generated by Django 4.2.7 on 2023-11-02 20:36
from typing import List

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies: List[str] = []

    operations = [
        migrations.CreateModel(
            name="CityDescriptorsORM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("city_description", models.CharField(max_length=2000)),
            ],
            options={
                "db_table": "city_descriptor",
            },
        ),
        migrations.CreateModel(
            name="ItineraryORM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("day", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("travel_method", models.CharField(max_length=50)),
                ("travel_time", models.CharField(max_length=50)),
                ("morning_activity", models.CharField(max_length=150)),
                ("afternoon_activity", models.CharField(max_length=150)),
                ("evening_activity", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "itineraries",
            },
        ),
        migrations.CreateModel(
            name="SearchHistoryORM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "search_history",
            },
        ),
        migrations.CreateModel(
            name="UniqueSearchHistoryORM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("country", models.CharField(max_length=50)),
                ("specific_places", models.CharField(max_length=100)),
                ("num_days", models.IntegerField()),
            ],
            options={
                "db_table": "unique_search_history",
            },
        ),
        migrations.CreateModel(
            name="WorldCitiesORM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("city", models.CharField(max_length=50)),
                ("city_ascii", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("iso2", models.CharField(max_length=2)),
                ("iso3", models.CharField(max_length=3)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("population", models.IntegerField()),
                ("use_on_app", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "world_cities",
            },
        ),
        migrations.CreateModel(
            name="UserSavedItineraryORM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.IntegerField()),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                (
                    "ush",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.uniquesearchhistoryorm",
                    ),
                ),
            ],
            options={
                "db_table": "user_saved_itinerary",
            },
        ),
        migrations.AddConstraint(
            model_name="uniquesearchhistoryorm",
            constraint=models.UniqueConstraint(
                fields=("country", "specific_places", "num_days"),
                name="constraint__unique_search_history",
            ),
        ),
        migrations.AddField(
            model_name="searchhistoryorm",
            name="unique_search_history",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.uniquesearchhistoryorm",
            ),
        ),
        migrations.AddField(
            model_name="itineraryorm",
            name="unique_search_history",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.uniquesearchhistoryorm",
            ),
        ),
        migrations.AddField(
            model_name="citydescriptorsorm",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.worldcitiesorm"
            ),
        ),
    ]
