# Generated by Django 4.2.7 on 2023-11-02 21:32
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="usersaveditineraryorm",
            constraint=models.UniqueConstraint(
                fields=("user_id", "ush_id", "from_date", "to_date"),
                name="constraint__user_saved_itinerary",
            ),
        ),
    ]
