# Generated by Django 4.2.7 on 2023-11-12 23:35
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_cityclimateorm_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="citydescriptorsorm",
            constraint=models.UniqueConstraint(
                fields=("city_id", "city_description"),
                name="constraint__unique_city_description",
            ),
        ),
    ]
