# Generated by Django 4.2.7 on 2023-11-13 23:12
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_citydescriptorsorm_constraint__unique_city_description"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="citydescriptorsorm",
            name="constraint__unique_city_description",
        ),
        migrations.AddConstraint(
            model_name="citydescriptorsorm",
            constraint=models.UniqueConstraint(
                fields=("city_id",), name="constraint__unique_city_id"
            ),
        ),
    ]
