# Generated by Django 4.2.7 on 2023-11-18 13:04
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "api",
            "0006_remove_citydescriptorsorm_constraint__unique_city_description_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ItineraryItemsORM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("item", models.CharField(max_length=100)),
                ("tag", models.CharField(max_length=25)),
                ("duration_minutes", models.IntegerField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.worldcitiesorm",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
