# Generated by Django 4.2.7 on 2023-11-20 21:42
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_itineraryitemsorm_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityCostOfLivingORM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("category", models.CharField(max_length=200)),
                ("sub_category", models.CharField(max_length=200)),
                ("cost", models.FloatField()),
                ("currency", models.CharField(default="EUR", max_length=200)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.worldcitiesorm",
                    ),
                ),
            ],
            options={
                "db_table": "city_cost_of_living",
            },
        ),
        migrations.AddConstraint(
            model_name="citycostoflivingorm",
            constraint=models.UniqueConstraint(
                fields=("city_id", "category", "sub_category"),
                name="constraint__unique_city_id_category_sub_category",
            ),
        ),
    ]
