# Generated by Django 4.2.7 on 2023-11-29 18:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_citycostoflivingorm_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniqueSavedItineraryORM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.IntegerField()),
                ("blob", models.JSONField()),
            ],
            options={
                "db_table": "unique_saved_itinerary",
            },
        ),
    ]
