# Generated by Django 4.2.7 on 2023-12-08 11:25
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_uniquesaveditineraryorm"),
    ]

    operations = [
        migrations.CreateModel(
            name="GygCityMapORM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("gyg_id", models.IntegerField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.worldcitiesorm",
                    ),
                ),
            ],
            options={
                "db_table": "gyg_city_map",
            },
        ),
    ]
