# Generated by Django 4.2.7 on 2023-12-15 14:50
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_gygcitymaporm"),
    ]

    operations = [
        migrations.AddField(
            model_name="uniquesaveditineraryorm",
            name="city",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="uniquesaveditineraryorm",
            name="country",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="uniquesaveditineraryorm",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="uniquesaveditineraryorm",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
