# Generated by Django 4.2.7 on 2024-01-12 11:23
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_uniquesaveditineraryorm_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itineraryitemsorm",
            name="description",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="itineraryitemsorm",
            name="lat",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="itineraryitemsorm",
            name="long",
            field=models.FloatField(null=True),
        ),
    ]
