# Generated by Django 4.2.7 on 2024-01-19 14:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_itineraryitemsorm_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citydescriptorsorm",
            name="city_description",
            field=models.CharField(max_length=2500),
        ),
    ]
