"""empty message

Revision ID: 5972611791e1
Revises: a494150b667f
Create Date: 2023-10-09 16:06:08.723321

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "5972611791e1"
down_revision = "a494150b667f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("city_descriptor", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["city_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("city_descriptor", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
