"""empty message

Revision ID: a52ea3e5b6c6
Revises: 5972611791e1
Create Date: 2023-10-28 12:29:38.426338

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "a52ea3e5b6c6"
down_revision = "5972611791e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_saved_ininerary",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("ush_id", sa.String(length=50), nullable=False),
        sa.Column("from_date", sa.DateTime(), nullable=True),
        sa.Column("to_date", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_saved_ininerary")
    # ### end Alembic commands ###
