"""Initial migration

Revision ID: a6857c462f25
Revises:
Create Date: 2023-09-08 13:28:45.603034

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "a6857c462f25"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("num_days", sa.Integer(), nullable=False),
        sa.Column("country", sa.String(length=50), nullable=False),
        sa.Column("specific_places", sa.String(length=100), nullable=False),
        sa.Column("day", sa.String(length=50), nullable=True),
        sa.Column("travel_method", sa.String(length=50), nullable=True),
        sa.Column("travel_time", sa.String(length=50), nullable=True),
        sa.Column("morning_activity", sa.String(length=100), nullable=True),
        sa.Column("afternoon_activity", sa.String(length=100), nullable=True),
        sa.Column("evening_activity", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("country", "specific_places", "num_days"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("search_history")
    # ### end Alembic commands ###
