repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: fix-byte-order-marker
- repo: https://github.com/ambv/black
  rev: 23.10.1
  hooks:
  - id: black
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.12.0
  hooks:
  -   id: reorder-python-imports
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.1.3'
  hooks:
    - id: ruff
      exclude: 'asgi.py'
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.6.1
  hooks:
  - id: mypy
    name: Run type checks
    args: ["--ignore-missing-imports", "--install-types", "--non-interactive"]
- repo: local
  hooks:
  - id: migrations-check
    language: system
    name: Check for uncreated migrations.
    entry: bash -c "./manage.py makemigrations --check --dry-run"
    types: ["python"]
    pass_filenames: false
