"""empty message

Revision ID: 1ef30f8ef019
Revises: 8753d8622fba
Create Date: 2023-10-28 12:53:51.794733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef30f8ef019'
down_revision = '8753d8622fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_saved_itinerary', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id', 'ush_id', 'from_date', 'to_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_saved_itinerary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
