"""changed to two tables

Revision ID: 56cc185a3588
Revises: a6857c462f25
Create Date: 2023-09-14 09:16:41.622614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56cc185a3588'
down_revision = 'a6857c462f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unique_search_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num_days', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('specific_places', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country', 'specific_places', 'num_days')
    )
    op.create_table('iteneraries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unique_search_history_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=50), nullable=True),
    sa.Column('travel_method', sa.String(length=50), nullable=True),
    sa.Column('travel_time', sa.String(length=50), nullable=True),
    sa.Column('morning_activity', sa.String(length=100), nullable=True),
    sa.Column('afternoon_activity', sa.String(length=100), nullable=True),
    sa.Column('evening_activity', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['unique_search_history_id'], ['unique_search_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('search_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_history',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('specific_places', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('day', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('travel_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('travel_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('morning_activity', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('afternoon_activity', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('evening_activity', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('country', 'specific_places', 'num_days', name='search_history_pkey')
    )
    op.drop_table('iteneraries')
    op.drop_table('unique_search_history')
    # ### end Alembic commands ###
