"""empty message

Revision ID: 78d666900267
Revises: 2515e55b7a11
Create Date: 2023-09-15 13:22:21.427380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d666900267'
down_revision = '2515e55b7a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iteneraries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iteneraries', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
