# Generated by Django 4.2.7 on 2023-11-03 15:13
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_usersaveditineraryorm_constraint__user_saved_itinerary"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="uniquesearchhistoryorm",
            name="constraint__unique_search_history",
        ),
        migrations.RemoveConstraint(
            model_name="usersaveditineraryorm",
            name="constraint__user_saved_itinerary",
        ),
        migrations.RenameField(
            model_name="uniquesearchhistoryorm",
            old_name="specific_places",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="usersaveditineraryorm",
            old_name="ush",
            new_name="unique_search_history",
        ),
        migrations.AddConstraint(
            model_name="uniquesearchhistoryorm",
            constraint=models.UniqueConstraint(
                fields=("country", "city", "num_days"),
                name="constraint__unique_search_history",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersaveditineraryorm",
            constraint=models.UniqueConstraint(
                fields=("user_id", "unique_search_history_id", "from_date", "to_date"),
                name="constraint__user_saved_itinerary",
            ),
        ),
    ]
