# Generated by Django 4.2.7 on 2023-11-04 13:24
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "api",
            "0003_remove_uniquesearchhistoryorm_constraint__unique_search_history_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CityClimateORM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("month", models.CharField(max_length=15)),
                ("low", models.IntegerField()),
                ("high", models.IntegerField()),
                ("rainfall", models.IntegerField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.worldcitiesorm",
                    ),
                ),
            ],
            options={
                "db_table": "city_climate",
            },
        ),
        migrations.AddConstraint(
            model_name="cityclimateorm",
            constraint=models.UniqueConstraint(
                fields=("city_id", "month"),
                name="constraint__unique_city_climate_month",
            ),
        ),
    ]
