version: '3'
services:
  db:
    build: ./postgresql-directory  # Replace with your PostgreSQL directory path
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
